# Intro_To_Numpy 

In [1]:
# NumPy provides efficient data operations on arrays and matrices
import numpy as np 

In [2]:
a=np.array([1,2,3,4,3,2,1]) #array is native to numpy
a 

array([1, 2, 3, 4, 3, 2, 1])

In [3]:
#List can colllect heterogeneous data types. 
#An array collect homogeneous data type.

#List cannot manage arithmetic operations.
#Array can manage arithmetic operations

In [4]:
np.sort(a)

array([1, 1, 2, 2, 3, 3, 4])

In [5]:
a=np.array([[1,2,3,4],[5,6,7,8]]) #2D array
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a.size 

8

In [7]:
a.shape 

(2, 4)

In [8]:
a=a.reshape(4,2)
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [9]:
a[1,0] #accesing values 

3

In [10]:
a.min()

1

In [11]:
#return the index of the lowest element from the array.
np.argmin(a)

0

In [12]:
a.max()

8

In [13]:
#returns the index of the max element from the array
np.argmax(a)

7

In [14]:
a.sum() #sum of all elements

36

In [15]:
a.sum(axis=0) #axis 0 means operation will be performed on rows

array([16, 20])

In [16]:
a.sum(axis=1)  #axis 1 means operation will be performed on columns

array([ 3,  7, 11, 15])

In [17]:
# linepsace creates an array with evenly spaced float numbers over a specified interval.
#np.linespace(start,end,no.of samples)

np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [18]:
#n random integer samples within a range

np.random.randint(1,10,8)  #Low is inclusive, High is exclusive  

array([2, 7, 7, 3, 7, 3, 6, 1])

In [19]:
np.random.randint(5,None,5)

#if high is none then, range is from zero to low

array([0, 2, 4, 4, 0])

In [20]:
#n random float samples

np.random.random(3) 

array([0.45815774, 0.21605544, 0.87010225])

In [21]:
# create an array of 0

np.zeros((2,4),dtype="int")
#if desired data type not mentioned then default ‘float’

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
# create an array of 1

np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# create an array of random value

np.full((2,3),fill_value=9)

array([[9, 9, 9],
       [9, 9, 9]])

In [24]:
#Create an identity matrix with specified dimensions

np.identity(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
#returns all the unique elements sorted & count

arr=np.array([1,1,2,2,3,3,3,4,5,6,7,8,9])
np.unique(arr,return_counts=True)  

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([2, 2, 3, 1, 1, 1, 1, 1, 1], dtype=int64))

In [26]:
#Count all the non-zero elements

arr1=np.array([0,1,2,3,0,2,3])
np.count_nonzero(arr1)

5

In [27]:
#return the indices of non-zero elements

np.argwhere(arr1)

array([[1],
       [2],
       [3],
       [5],
       [6]], dtype=int64)

## Set Operations

In [28]:
# Common Elements

ar1 = np.array([1,2,3,4,5,6,7])
ar2 = np.array([5,6,7,8,9,10])

np.intersect1d(ar1,ar2,return_indices=True)
# Returns common Elements & Indices of common elements

(array([5, 6, 7]),
 array([4, 5, 6], dtype=int64),
 array([0, 1, 2], dtype=int64))

In [29]:
# Difference

ar1 = np.array([1,2,3,4,5,6,7])
ar2 = np.array([5,6,7,8,9,10])

np.setdiff1d(ar1,ar2)
# returns unique elements from array 1 that are not present in arr2.

array([1, 2, 3, 4])

In [30]:
# Unique Elements From Both Arrays

ar1 = np.array([1,2,3,4,5,6,7])
ar2 = np.array([5,6,7,8,9,10])

np.setxor1d(ar1,ar2)

array([ 1,  2,  3,  4,  8,  9, 10])

In [31]:
# combine both arrays into one (Union)

ar1 = np.array([1,2,3,4,5,6,7])
ar2 = np.array([5,6,7,8,9,10])

np.union1d(ar1,ar2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Splitting

In [32]:
#Horizontal Split

A = np.array([[1,2,3,4],[5,6,7,8]])
np.hsplit(A,4) #splits the data into four equal parts

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [33]:
# Vertical Split

A = np.array([[1,2,3,4],[5,6,7,8]])
np.vsplit(A,2) #splits the data into two equal parts

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

## Stacking

In [34]:
#  Horizontal Stacking -> appends one array at the end of another.

a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])

np.hstack((a,b))


array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

In [35]:
# Vertical Stacking -> stack one array on top of another.

a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])

np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

## Comparing Two Arrays

In [36]:
# whether two arrays are approx. equal to each other based on some tolerance value

a1 = np.array([1,2,3,4])
b1 = np.array([1.1,2.1,3.1,4.1])

tolerance = 0.2 
print(np.allclose(a1,b1,tolerance))

tolerance = 0.05
print(np.allclose(a1,b1,tolerance))

True
False


In [37]:
# whether two arrays are exactly equal

a2=np.array([1,8,27,64])
b2=np.array([1,8,27,68])

np.equal(a2,b2)

array([ True,  True,  True, False])